### ISSUE TITLE
[Question] 关于脚本执行 main.py的问题

### ISSUE THREAD

**Issue by arrosev** [jumpserver/applets#30]
**请描述您的问题.**
我可以执行除py main.py之外的额外命令吗？我的项目需要使用到venv，然后我想先切换到虚拟环境再执行py main.py。

**Comment by wojiushixiaobai** [comment]
这里只是定义入口，你可以在你自己的 app 代码入口进行虚拟环境定义。
或者将你的程序发布成 exe 格式，这样其他用户也能使用
